// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, owner_id, created_at, updated_at
`

type CreateProjectParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.ID, arg.Name, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectById = `-- name: GetProjectById :one
SELECT id, name, owner_id
FROM projects
WHERE id = $1 LIMIT 1
`

type GetProjectByIdRow struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetProjectById(ctx context.Context, id uuid.UUID) (GetProjectByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectById, id)
	var i GetProjectByIdRow
	err := row.Scan(&i.ID, &i.Name, &i.OwnerID)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name, owner_id 
FROM projects
WHERE name = $1
`

type GetProjectByNameRow struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetProjectByName(ctx context.Context, name string) (GetProjectByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectByName, name)
	var i GetProjectByNameRow
	err := row.Scan(&i.ID, &i.Name, &i.OwnerID)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, owner_id, created_at, updated_at 
FROM projects
ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
