// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, name, project_id, creator_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, project_id, creator_id, status, label, created_at, updated_at
`

type CreateTaskParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	ProjectID uuid.UUID `json:"project_id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.Name,
		arg.ProjectID,
		arg.CreatorID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.CreatorID,
		&i.Status,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectTasks = `-- name: ListProjectTasks :many
SELECT id, name, project_id, creator_id, status, label, created_at, updated_at
FROM tasks
WHERE project_id = $1
`

func (q *Queries) ListProjectTasks(ctx context.Context, projectID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listProjectTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.CreatorID,
			&i.Status,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
